dist: trusty
sudo: required

language: go


services:
- docker

before_install:
  - sudo apt-get remove docker docker-engine
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker version
  - docker info
  # prepare docker test requirements
  - make update-dependencies
  - docker build -t registry.heroku.com/"$HEROKU_APPNAME"/web .
  - docker login -u "$HEROKU_EMAIL" -p "$HEROKU_APIKEY" registry.heroku.com
  - docker push registry.heroku.com/"$HEROKU_APPNAME"/web
